# Generated by Django 4.2.1 on 2023-05-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='questao_texto',
        ),
        migrations.AddField(
            model_name='questao',
            name='questao_descricao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questao',
            name='questao_titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
