# Generated by Django 4.2 on 2023-05-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_questao_questao_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.questao'),
        ),
    ]
